export const interActief = [
    "#Bibz",
    "A Night In Paris",
    "A-Eskwadraat",
    "Abacus",
    "Abscint",
    "Advisory board",
    "Alembic",
    "Alpequalpeqi",
    "Andrea Rijkeboer",
    "Animal on spit drink",
    "Applied Mathematics",
    "Arago",
    "Arie Duijvestijn",
    "Ascend",
    "Assembly",
    "Astatine",
    "AstronomIA",
    "Atlantis",
    "Audit Committee",
    "BIT",
    "BIT's Lit",
    "Back on Track",
    "Bart",
    "Bartenders",
    "Batavierenrace",
    "Belastingdienst",
    "BetterBe",
    "Bits Please!",
    "Blast From The Past",
    "Board Workload Taskforce",
    "Bob Ross",
    "Bram",
    "Bronto DB",
    "C",
    "C#",
    "C++",
    "CSS",
    "Cantus",
    "Canvas",
    "Capgemini",
    "Casino Night",
    "CelerIT",
    "ChaChi",
    "Chairman",
    "Chris",
    "Christiaan Huygens",
    "CoLeX",
    "Communiqué",
    "Computer Architecture for Embedded Systems (CAES)",
    "Computer Systems",
    "ConcepT",
    "Constitution Drink",
    "Cooking Club",
    "Cover",
    "CreativIT",
    "Culture Committee",
    "Cyber Physical Systems",
    "Cyber Security",
    "DESDA",
    "Daddy Kool",
    "Daedalus",
    "Dani",
    "Daniël",
    "Das Mooi!",
    "Data & Information",
    "Data Management & Biometrics (DMB)",
    "Data Science & Artificial Intelligence: Seeing through the hype",
    "Data Science & Technology",
    "De Leidsche Flesch",
    "DeCo",
    "Denarius",
    "Design and Analysis of Communication Systems (DACS)",
    "Di Stephano",
    "DiesCie",
    "Dilan",
    "Dimensie",
    "Dipso",
    "Discrete Stuctures & Efficient Algorithms",
    "Disseminate",
    "Doina Bucur",
    "Don't Panic",
    "Duru",
    "ECA",
    "EEMCS Trip",
    "ENIAC",
    "EducaCie",
    "Educational Affairs",
    "Eelco Eerenberg",
    "Electrical Engineering",
    "Eleven Beers Tour",
    "Escape the City",
    "Evolve",
    "Ex on the beach",
    "Exact Online",
    "External Affairs",
    "Extraterrestrial Encounter",
    "FMF",
    "Faiza Bukhsh",
    "Faizan Ahmed",
    "Fantasia",
    "Fiasco",
    "Formal Methods and Tools (FMT)",
    "Fortes Solutions",
    "Frank van Mourik",
    "FreshCo",
    "Freshmen Bowling",
    "Fuente",
    "Full House",
    "GEWIS",
    "GMA",
    "GMM",
    "GameCie",
    "Games of Gallia",
    "Gender in the blender drink",
    "Gilian",
    "HERO's",
    "Hal B",
    "Han Joosten",
    "Harambee",
    "Haskell",
    "Hein",
    "Hephaestus",
    "Het Genootschap BIT",
    "Horus",
    "Hot Ones",
    "How to Borrel",
    "Human Media Interaction (HMI)",
    "Hyper",
    "I/O Vivat",
    "IA room",
    "IAPC",
    "IBCC",
    "Ideefiks",
    "Illuminate",
    "Insomnia",
    "Inspire",
    "Intelligent Interaction Design",
    "Inter-Actief",
    "InterRailing",
    "Internal Affairs",
    "Internet Science & Technology",
    "Iris van Duiven",
    "Isaac Newton",
    "Java",
    "JavaScript",
    "Jelle",
    "Jelte Zeilstra",
    "Job Ulfman",
    "Jochem",
    "Johan Noltes",
    "Karel de Jonge",
    "Kevin Alberts",
    "Kick-IT",
    "Komma",
    "Lahmacun Lecture",
    "Lars",
    "Lorem Ipsum",
    "Lunch lectures",
    "MBasement",
    "Maaike Butink",
    "Maarten",
    "MafIA",
    "Mahboobeh Zangiabady",
    "Mariska",
    "Mathijs",
    "Maurice van Keulen",
    "MedIA",
    "Met Mate(n)",
    "Michael",
    "MinIAture",
    "Miranda",
    "MobiliIT",
    "MonkIA",
    "Movie park Germany",
    "Nacir Bouali",
    "Networking Systems",
    "Nexus",
    "Niels",
    "NostalgIA",
    "OS",
    "OVSoftware",
    "Oktoberfest",
    "Oliver",
    "Open Up",
    "Pandora",
    "Paradoks",
    "PartyCo",
    "Pearls of Computer Science",
    "Pervasive Systems (PS)",
    "Pieter-Tjerk de Boer",
    "Primavera",
    "Programming Paradigms",
    "Project Diamond",
    "Proto",
    "Python",
    "Quirijn",
    "RIAlly",
    "Race Cafe Australia",
    "RedShell",
    "Rianne de Jong",
    "Rom Langerak",
    "Roomboter",
    "Rosan",
    "SAGA",
    "SNiC",
    "SQL",
    "STORM",
    "SU",
    "Sander",
    "Sanne Spuls",
    "Scintilla",
    "Secretary",
    "Services and Cybersecutiry (SCS)",
    "Sirius",
    "Sjoerd van der Spoel",
    "Slagwaardig",
    "Smart Spaces",
    "SocCie",
    "Software Systems",
    "Software Technology",
    "Spijkertjes",
    "StAf",
    "Step into the shadows",
    "Sticky",
    "Stress",
    "Study Evening",
    "Study Tour",
    "Study tour",
    "Sudo",
    "Summer Sounds",
    "Sweet 16 drink",
    "SymCie",
    "Symposium",
    "SysCom",
    "TAPC",
    "TaCoS",
    "Technical Computer Science",
    "Tegel",
    "Thalia",
    "Tom",
    "Tom van Dijk",
    "Toverland",
    "Treasurer",
    "Tristan",
    "Tu the moon AD",
    "Turings Tower",
    "Twan",
    "UToberfest",
    "Vadim Zaytsev",
    "Vice-Chair",
    "Voortman Steel Group",
    "WISO",
    "WWW",
    "Wallace Ugulino",
    "Wander",
    "Web Science",
    "Wesley",
    "Wie Geet Lös",
    "Wild Wild West",
    "Willem",
    "Wireshark",
    "Wout",
    "Wouter",
    "XmasCie",
    "Yahtzee",
    "Yolo",
    "Yorinf",
    "Zephyrus",
    "ZombIA",
    "Zoom Out",
    "aXi",
    "booking.com",
    "chmod",
    "echo",
    "grep",
    "kill -9",
    "mkdir",
    "nano",
    "netstat",
    "sudo",
    "systemctl",
    "touch",
    "via",
    "wget",
] // end interActief