# This is a basic workflow to help you get started with Actions

name: CI - Release

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      # Set up Node and
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          
      # Install node modules
      - name: Install node modules
        run: npm ci
        
      # Create production build
      - name: Create production build
        run: npm run build

      # Get current date for release name
      - name: Get current date
        id: date
        run: echo "name=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      
      # Zip Public folder for Release
      - name: Zip Build
        run: zip -r build.zip ./public/*
    
      # Release
      - name: Git Release
        uses: anton-yurchenko/git-release@v3.4.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: |
              build.zip
